### ISSUE TITLE
Is there any example of use the env vars? (eg: YARN_NPM_AUTH_TOKEN)

### ISSUE THREAD

**Issue by tiavina-mika** [hongaar/semantic-release-yarn#310]
is this used in `.yarnrc` like this:

npmAuthToken: ${YARN_NPM_AUTH_TOKEN}
?

**Comment by hongaar** [comment]
Specifying `npmAuthToken` like this in `.yarnrc` is not strictly needed. Simply add the environment variable `YARN_NPM_AUTH_TOKEN` and you're good to go!
